services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #read-only

  node-app:
    build: .
    image: caitano09/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo
  
  mongo:
    image: mongo:4.4 #usando essa versão para funcionar na maquina virtual
    environment: 
      MONGO_INITDB_ROOT_USERNAME: sanjeev
      MONGO_INITDB_ROOT_PASSWORD: mypassword   
    volumes:
      - mongo-db:/data/db  

  redis:
    image: redis

volumes:
  mongo-db: